version: '3.8'
services:
  backend:
    environment:
      MONGODB_URI: mongodb://mongodb:27017/shorten
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
