micronaut:
  application:
    name: url-shortener
app:
  baseUrl: http://localhost:8080/
datasources:
  default:
    driverClassName: com.mongodb.client.MongoClient
mongodb:
  package-names: com.example.urlshortener.model
  connection-pool:
    max-size: 5
  uri: mongodb://localhost:27017/shorten

